version: "2"
run:
  # The default timeout is 1m, which can fail in CI if your project gets big or dependencies are slow to download.
  timeout: 5m

linters:
  default: none
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style

    gosec:
      # We exclude G104 (unhandled errors) here because the 'errcheck' linter
      # already does this job much better, and we don't want duplicate warnings.
      excludes:
        - G104
  enable:
    - errcheck # Force error handling
    - bodyclose # CRITICAL: Ensures HTTP response bodies are closed.
    - gosec # Scans for security flaws.

    # General static analysis / code quality / performance:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gocritic
    - misspell
    - revive

  exclusions:
    paths:
      - vendor

formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/GenesisEducationKyiv/software-engineering-school-6-0-walking-wisely

issues:
  # By default, golangci-lint stops showing issues after it finds 50 of the same type.
  # Set to 0 to show EVERYTHING, so developers don't fix 50 errors only to discover 50 more.
  max-issues-per-linter: 0
  max-same-issues: 0
